[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.17", features=["full", "extra-traits"]}
quote = { workspace = true }
proc-macro2 = { workspace = true }


[features]
nightly = []